In [310]:
#Section 1 EDA
    #Understand the columns.
	#Examine data visually.
	#Run any additional numeric tests.


import pandas as pd
import numpy as np

bank_full = pd.read_csv('bank-full.csv', delimiter=";")

bank_full.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [311]:
bank_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [312]:
bank_full.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [313]:
print(bank_full.dtypes)

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [314]:
bank_full['education'].unique()

array(['basic.4y', 'high.school', 'basic.6y', 'basic.9y',
       'professional.course', 'unknown', 'university.degree',
       'illiterate'], dtype=object)

In [315]:
#Section 2 Data Preparation
    #Handle nulls.
	#Scale variables as necessary.
	#Encode variables as necessary.
	#Drop features you don't want.
	#Generate additional features if you want.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import OneHotEncoder

bank_full.dropna() #dropping rows that contain NAs

encoder = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

bank_ohe = encoder.fit_transform(bank_full[['education']])
#I did my encoding on education to see if the level of education impacts getting a loan or not.

bank_combined = pd.concat([bank_full, bank_ohe], axis=1).drop(columns = ['education'])
#combined data back to the main dataframe and droped the main education column since I've encoded it. 
bank_combined

,age,job,marital,default,housing,loan,contact,month,day_of_week,duration,...,nr.employed,y,education_basic.4y,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown
0,56,housemaid,married,no,no,no,telephone,may,mon,261,...,5191.0,no,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,57,services,married,unknown,no,no,telephone,may,mon,149,...,5191.0,no,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,37,services,married,no,yes,no,telephone,may,mon,226,...,5191.0,no,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,40,admin.,married,no,no,no,telephone,may,mon,151,...,5191.0,no,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,56,services,married,no,no,yes,telephone,may,mon,307,...,5191.0,no,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,no,yes,no,cellular,nov,fri,334,...,4963.6,yes,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
41184,46,blue-collar,married,no,no,no,cellular,nov,fri,383,...,4963.6,no,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
41185,56,retired,married,no,yes,no,cellular,nov,fri,189,...,4963.6,no,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
41186,44,technician,married,no,no,no,cellular,nov,fri,442,...,4963.6,yes,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
41187,74,retired,married,no,yes,no,cellular,nov,fri,239,...,4963.6,no,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [316]:

titles = list(bank_combined.columns)
titles

order = ['age', 'job', 'marital', 'default','housing','loan','contact','month','day_of_week','duration','campaign','pdays','previous','poutcome','emp.var.rate','cons.price.idx','cons.conf.idx','euribor3m','nr.employed','education_basic.4y','education_basic.6y','education_basic.9y','education_high.school','education_illiterate','education_professional.course', 'education_university.degree', 'education_unknown','y',]
bank_combined = bank_combined[order]
bank_combined

bank_combined.dtypes
#reording column "y" to the end because it was placed in the middle of my integer data

age                                int64
job                               object
marital                           object
default                           object
housing                           object
loan                              object
contact                           object
month                             object
day_of_week                       object
duration                           int64
campaign                           int64
pdays                              int64
previous                           int64
poutcome                          object
emp.var.rate                     float64
cons.price.idx                   float64
cons.conf.idx                    float64
euribor3m                        float64
nr.employed                      float64
education_basic.4y               float64
education_basic.6y               float64
education_basic.9y               float64
education_high.school            float64
education_illiterate             float64
education_professional.course    float64
education_university.degree      float64
education_unknown                float64
y                                 object
dtype: object

In [317]:
#Section 3 Model Selection
	#Use model "DecisionTreeClassifier"
	#Use Model "SGDClassifier"

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier



X = bank_combined.iloc[:, 15:27]
Y = bank_combined.iloc[:, 27]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=42, test_size = 0.3)

dtree = DecisionTreeClassifier()

dtree.fit(X_train, Y_train)


#The above is a simple decision tree classifier against my x and y variables.

DecisionTreeClassifier()

In [318]:
#This is my SGD Classifier Code

import pandas as pd
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

bank_sgd = make_pipeline(StandardScaler(), SGDClassifier(max_iter=1000, tol=1e-3))

bank_sgd.fit(X,Y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdclassifier', SGDClassifier())])

In [ ]:
#Section 4 Evaluation
    #Use a K-Fold cross validation to determine accuracy

from sklearn.model_selection import cross_val_score


banktree_rmses = -cross_val_score(dtree, X_test, Y_test, cv=5)

pd.Series(banktree_rmses).describe()

#I don't know why values are negative. However if they weren't negative it seems the accuracy is in the high 80% range so it's fairly effective at predicting values.

count    5.000000
mean    -0.887190
std      0.005891
min     -0.895589
25%     -0.889563
50%     -0.886686
75%     -0.884257
max     -0.879854
dtype: float64

In [ ]:
from sklearn.model_selection import cross_val_score


banksgd_rmses = -cross_val_score(bank_sgd, X_test, Y_test, cv=5)

pd.Series(banksgd_rmses).describe()

#hmmm my sgd classifier is also negative, I did something wrong in my model. Like my decision tree, the SGD is also high 80% if you ignore the negatives, effective at prediciting values. 


#However, a note that since both models are outputting negatives it means I have done something wrong and it's not predicting my outcomes correctly at all, and it's not correct to ignore the negatives--

count    5.000000
mean    -0.885894
std      0.003861
min     -0.887945
25%     -0.887540
50%     -0.887495
75%     -0.887495
max     -0.878996
dtype: float64

In [322]:
#Section 5 Tuning
    #Use "GridSearchCV" to tune the best of the two classifiers above. Use 3-fold cross validation, test 9 parameter combinations

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline

bank_search = [
    { 'cons.price.idx': [5, 8, 10], 
    'cons.conf.idx': [4, 6, 8], 
    'euribor3m': [2, 4, 6], 
    'nr.employed': [2, 4, 6]},
    ]

bank_gridsearch = GridSearchCV(bank_combined, bank_search, cv=3, scoring="neg_root_mean_squared_error")

#EEROR ON CODE -- bank_gridsearch.fit(X_train, Y_train)
#My code works up unti this grid fit, I cannot figure out why my search fit is not working. I've read the gridsearchCV library guide, and followed the demo. Not sure why it's failing.

In [ ]:
#Section 6 Conclusion
    #Submit your report of the best models performance. Provide two or three ideas for further improvements

#Report 
#I've left comments throughout my code blocks which summarize what it's doing. 
#However, I read the csv in and seaparated on the ;.I then encoded education because I wanted to see if education had any impact on whether or not the customer received a loan. 
#After that I combined my datasets with the new encoding, and sorted my y column to the end because it was inbetween other columns I wanted to perform analysis on. 
#Both predictive models ran, however most likely ran incorrectly, and the only part that I could not get to work was the gridsearch fit to my training data. 


#Thank you.